Docs/pr_template.md
#What does this pr do? 
1. Adds a pr template for PR requests.
=> added pr template

Docs/PULL_REQUEST_TEMPLATE.md, package-lock.json, package.json, src/App/App.tsx, src/index.tsx
1. Adds routes for all initial pages.
2. Removes comments from PR template.
=> added initial routes for current pages

src/App/App.tsx, src/Screening-page/ScreeningPage.css, src/Screening-page/ScreeningPage.tsx, src/Screening1/Screening1.tsx, src/Screening2/ProgressBar.tsx, src/Screening2/Screening2.css, src/Screening2/Screening2.tsx
1. Adds a progress bar for the CAST Screening test.
2. Updates the results page with colored text for different rankings.
=> Screening test/jw

src/Header/Header.tsx, src/Information-page/InformationPage.css, src/Information-page/InformationPage.tsx, src/Providers-page/ProvidersPage.css, src/Providers-page/ProvidersPage.tsx, src/Screening-page/ScreeningPage.css
1. Created information page
2. Adjusted font size to match across all the website
=> adjusted font size for all pages

src/Provider-login/LoginPage.css, src/Provider-login/LoginPage.tsx, src/Signup/Signup.css
1. Styles the login page and sign up pages to fit all screen sizes.
1. By looking at the css files for both the login component and signup component. 
=> updated media quieries for login and sign up pages

src/Providers-page/ProvidersPage.css
1. Minor tweaks to styling on desktop view. Quick fixes to allow mobile view, some provider cards made need additional tweaking based upon how much data fills in the card. Will continue to edit styling, just wanted some kind of mobile view for now.
=> further styling to grid layout for mobile view

src/Providers-page/ProviderModal.tsx
1. modal only closes when 'x' is clicked
=> fixed modal

cypress.config.ts, cypress/e2e/aboutus.cy.ts, cypress/e2e/casttest.cy.ts, cypress/e2e/contactus.cy.ts, cypress/e2e/footer.cy.ts, cypress/e2e/header.cy.ts, cypress/e2e/homepage.cy.ts, cypress/e2e/informationpage.cy.ts, cypress/e2e/pagenotfound.cy.ts, cypress/e2e/provider-login.cy.ts, cypress/e2e/providerspage.cy.ts, cypress/e2e/screeningpage.cy.ts, cypress/e2e/signuppage.cy.ts, cypress/fixtures/example.json, cypress/support/commands.ts, cypress/support/e2e.ts, package-lock.json, package.json, src/Header/Header.css, src/Header/Header.tsx, src/Homepage/Homepage.tsx
1. Initializes the cypress testing specs for all components within the app. 
=> cypress specs created for testing

cypress/e2e/casttest.cy.ts, cypress/e2e/pagenotfound.cy.ts, cypress/e2e/provider-login.cy.ts, cypress/e2e/screeningpage.cy.ts, cypress/e2e/signuppage.cy.ts, src/Provider-login/LoginPage.tsx, src/Screening-page/ScreeningPage.tsx, src/Screening2/Screening2.tsx, tsconfig.json
1. Adds cypress testing for the screening page and CAST test.
2. Updates the json and ts.config files to allow cypress testing.
=> cypress testing for the screening page and CASt test

cypress/e2e/aboutus.cy.ts, cypress/e2e/contactus.cy.ts, cypress/e2e/footer.cy.ts, cypress/e2e/homepage.cy.ts, cypress/e2e/informationpage.cy.ts, src/ContactUs/ContactUs.css, src/Header/Header.tsx, src/Homepage/Homepage.css, src/Homepage/Homepage.tsx
1. Added cypress tests for about us page, contact us page, footer, information page
=> added cypress tests

src/App/App.tsx, src/Provider-edit/CountiesModal.css, src/Provider-edit/CountiesModal.tsx, src/Provider-edit/InsuranceModal.css, src/Provider-edit/InsuranceModal.tsx, src/Provider-edit/ProviderEdit.css, src/Provider-edit/ProviderEdit.tsx
1. Edit page
2. Not functioning yet, just bunch of input fields
=> added edit-page

cypress/e2e/providerspage.cy.ts, cypress/fixtures/providerspage.json, cypress/support/commands.tsx, src/Providers-page/ProviderCard.tsx, src/Providers-page/ProviderModal.css, src/Providers-page/ProviderModal.tsx, src/Providers-page/ProvidersPage.css, src/Providers-page/ProvidersPage.tsx, src/Providers-page/SearchBar.css, src/Providers-page/SearchBar.tsx
1. Added more robust testing to the Providers Page and its Search Bar, mocking common user flows and searches of providers.
2. Edits to styling of modal providers Logo and a quick fix for tablet support. Will add a more fluid responsive design in future, possibly past MVP.
=> added further user flow testing within providers page and search bar

src/Provider-edit/ProviderEdit.css, src/Provider-edit/ProviderEdit.tsx
1. changed drop down options to have its own address for each locations
=> changed location options

src/Provider-edit/ProviderEdit.css, src/Provider-edit/ProviderEdit.tsx
1. Added user's view when logged in.
2. Adjusted for mobile view
=> added user view and adjusted for mobile view

src/Homepage/Homepage.css, src/Provider-edit/ProviderEdit.css
1. adjusted mobile view for county section in the homepage
=> fixed county section for mobile view

src/AboutUs/AboutUs.css, src/AboutUs/AboutUs.tsx, src/ContactUs/ContactUs.css, src/Header/Header.css, src/Information-page/InformationPage.css, src/Information-page/InformationPage.tsx, src/Provider-login/LoginPage.tsx, src/Providers-page/ProviderModal.css, src/Screening-page/ScreeningPage.css, src/Screening-page/ScreeningPage.tsx
1. Made sure the application is 100% Lighthouse passing for the Contact Us, Provider Login, Information Page, Screening Tools. Added proper sequentially-descending order heading elements, aria-labels, and contrast adjustments.
=> added further styling to improve user accessibility score on lighthouse

src/Provider-edit/ProviderEdit.tsx, src/Provider-login/LoginPage.tsx, src/Utility/ApiCall.ts
1. Fixes the issue of grabbing the logged in provider data.
2. Properly adds the data to the provider edit page.
=> got the data to finally render on the edit page

src/Provider-edit/ProviderEdit.css, src/Provider-edit/ProviderEdit.tsx, src/Provider-login/AuthProvider.tsx
1. gave a container for the edit page and styled it
=> added styling back to edit container

src/App/App.tsx, src/Provider-edit/ProviderEdit.css, src/Provider-edit/ProviderEdit.tsx, src/Provider-login/LoginPage.css, src/Provider-login/LoginPage.tsx
1. Added form fields for user data.
2. Fixed logout functionality for providerEdit page.
3. Fix landscape view for login page on smaller screens
=> Edit page functionality

src/App/App.css, src/Footer/Footer.css, src/Provider-edit/ProviderEdit.css, src/Provider-login/LoginPage.css, src/Provider-login/LoginPage.tsx
1. Fixed the issue with the footer keep overlapping
=> fixed footer issue that was overlapping

src/Provider-edit/ProviderEdit.css, src/Provider-edit/ProviderEdit.tsx, src/Provider-login/LoginPage.tsx, src/Utility/ApiCall.ts
1. Adds labels to the edit form for providers.
2. Adds coloring to label text.
3. Starts patch function in API calls. 
=> updated provider edit page forms

cypress/support/commands.tsx, src/Provider-edit/ProviderEdit.tsx
1. Still trying to make the patch feature work
=> trying to have patch working

cypress/e2e/providerEdit.cy.ts
1. basic cypress testing for providerEdit page. not completed yet, waiting for functionalities to be completed.
=> basic cypress testing for providerEdit page

src/Header/Header.css
1. Updates styling for certain screen sizes.
=> updated styling for navbar

src/Providers-page/ProvidersPage.tsx, src/Providers-page/SearchBar.tsx
1. Adds a suggestion dropdown when a user is typing to find a provider name.
=> added a suggestion portion for the filter input of provider names

src/App/App.tsx, src/Header/Header.css, src/Header/Header.tsx, src/Resources/Resources.tsx
1. Decreased excess white space for the header
2. Adjusted menu contents size for the media view
**After**
**Before**
**Mobile view**
=> adjusted navbar height and for media view

src/Information-page/InformationPage.css, src/Information-page/InformationPage.tsx, src/Provider-edit/ProviderEdit.tsx
1. Added functionality for the provider to cancel changes if they don't want to change them.
=> Cancel feature/jw

src/Providers-page/ProviderModal.css
1. Slight edits to heights of Modal.
=> style edits to modal bottom border

public/index.html, src/App/App.tsx, src/Provider-edit/ProviderEdit.tsx, src/Provider-login/LoginPage.tsx, src/SuperAdmin/SuperAdmin.css, src/SuperAdmin/SuperAdmin.tsx, src/SuperAdmin/SuperAdminEdit.css, src/SuperAdmin/SuperAdminEdit.tsx
1. Adds super admin pages and some functionality.
2. Also adds google analytics to the site to see how much traffic is coming in on the website/applicaiton. 
=> Super admin/jw

package-lock.json, package.json, src/Provider-edit/ProviderEdit.tsx, src/Providers-page/ProviderModal.tsx, src/Providers-page/ProvidersPage.tsx, src/SuperAdmin/SuperAdminEdit.css, src/SuperAdmin/SuperAdminEdit.tsx, src/Utility/Types.ts
1. Adds the updated last attribute for provider data.
2. Gets rid of targeting an element of "strong" and targets a class instead.
3. Removes multiple updated last dates since there's only one from the endpoint. 
=> updated to show last updated date and is formatted better

src/Homepage/Homepage.css
1. Fixed the issue with the counties being shown out of the media view screen
=> added overflow hidden and fixed the issue

src/FavoriteProviders-page/FavoriteProviders.css, src/Providers-page/ProviderCard.css, src/Providers-page/ProvidersPage.css
1. Minor adjustments to mobile screen view for the Providers Page.
=> minor adjustments to Providers Page screen responsiveness

Docs/PULL_REQUEST_TEMPLATE.md, src/Information-page/InformationPage.css, src/Provider-login/LoginPage.css, src/Provider-login/LoginPage.tsx, src/Providers-page/ProvidersPage.css, src/Resources/Resources.css
1. Updated login page for uniformed style across the website
2. adjusted font-sizes for some of the banner titles to match across the website
3. adjusted md file for PR template to change the cypress command to 'npx cypress open'
=> updated login page

src/Homepage/Homepage.css
1. Fixed the icons section on the homepage for better visibility across different mobile views
=> adjusted size of the icons for better view

src/Provider-edit/CountiesModal.css
1. Fixes county modal for mobile view. 
=> hopefully fixed county modal to fit better for mobile view

src/Provider-edit/AuthModal.css, src/Provider-edit/AuthModal.tsx, src/Provider-edit/ProviderEdit.tsx
Reverts utah-aba-finder/utah-aba-finder-fe#135
=> Revert "added continue edit button for warning modal for the provider edit page"

src/Provider-edit/AuthModal.css, src/Provider-edit/AuthModal.tsx
1. Adds continue button to edit data.
2. Fixes patch request. 
=> added continue editing button fixed PATCH update

src/Homepage/Homepage.css, src/Homepage/Homepage.tsx
1. Changes to welcome message
2. Prepped for sponsor section
=> made changes to welcome message and prepped for sponsor section

src/Homepage/Homepage.css
=> adjusted for mobile view

src/SuperAdmin/SuperAdminCreate.css, src/SuperAdmin/SuperAdminCreate.tsx
1. Super admin can now create a new provider
=> superAdmin can now create new provider

src/App/App.tsx
1. Forgot to push up the changes made in app.tsx
=> creating new provider as a super admin

src/SuperAdmin/SuperAdmin.css, src/SuperAdmin/SuperAdmin.tsx, src/SuperAdmin/SuperAdminCreate.css, src/SuperAdmin/SuperAdminCreate.tsx
1. There's a button to create new provider as a super admin
2. Super admin pages adjusted for better media view
=> create provider button for super admin , and adjusted for media view

src/Header/Header.css, src/Header/Header.tsx
1. consolidated the menu from 4 rows down to 3 for a cleaner look
Before
After
=> made the menu contents to fit and look better

src/App/App.tsx, src/Provider-edit/ProviderEdit.tsx, src/Provider-login/AuthProvider.tsx, src/Provider-login/LoginPage.tsx, src/SuperAdmin/SuperAdmin.tsx
1. Adds automatic logout and reroute one the JWT token expires (30 minutes)
2. Adds a message prior to auto logout if users are still logged in.
=> added automatic logout once the JWT token expires

src/SuperAdmin/SuperAdminCreate.css, src/SuperAdmin/SuperAdminCreate.tsx
1. Allows super admin to add counties for new providers
=> added an option to add counties

src/Signup/InsuranceModal.tsx, src/SuperAdmin/SuperAdminCreate.css, src/SuperAdmin/SuperAdminCreate.tsx
1. Trying to make the insurance button work; still work in progress.
=> adding insurance button WIP

src/Provider-edit/ProviderEdit.tsx
1. Fixes new location adding issue for providers.
=> updated locations to be updated/added for users. Accidentally deleted

src/Homepage/Homepage.tsx
1. Restored upcoming changes modal for whatever reason it wasn't there
=> restored upcoming changes modal

src/ContactUs/ContactUs.css, src/ContactUs/ContactUs.tsx, src/SuperAdmin/SuperAdminCreate.tsx
1. Adds a phone number and message to the contact us page.
=> updated contact us page with phone number

src/AboutUs/AboutUs.tsx, src/SuperAdmin/SuperAdminCreate.tsx
1. Adds success message and toastContainer/styling to show message upon successfully creating a new provider.
2. Removed Mel from the about us page.
=> added success message for creating a new user

src/SuperAdmin/SuperAdminCreate.tsx
1. Had to revert back to the old version due to mobile view issues
2. I'll work on the mobile view tomorrow
=> reverting back to the last version

src/Provider-edit/ProviderEdit.tsx, src/Providers-page/ProviderCard.tsx, src/SuperAdmin/SuperAdmin.tsx, src/SuperAdmin/SuperAdminCreate.tsx, src/SuperAdmin/SuperAdminEdit.tsx
1. Shows a toast success message upon creating a new provider. 
2. Changes the insurance modal for creating a new provider to the one from the provider-edit.
3. Updates a few small issues when adding new information for providers on the super admin edit. 
4. Fixes an issue on the providers card when a website doesn't have https or http before it.
=> Super admin create/jw

src/Providers-page/ProviderCard.css, src/Providers-page/SearchBar.css
1. To the search bar in mobile view.
=> Mobile restyling

src/Provider-edit/ProviderEdit.tsx, src/SuperAdmin/SuperAdmin.tsx, src/SuperAdmin/SuperAdminCreate.css, src/SuperAdmin/SuperAdminCreate.tsx, src/SuperAdmin/SuperAdminEdit.tsx, src/Utility/Types.ts
1. Adds .5 step for max and min ages served for both super admin and provider Admin since the default only allowed whole numbers.
=> Updates to admin edits/jw

package-lock.json, package.json, src/Donations/CheckoutForm.tsx, src/Donations/Donations.css, src/Donations/Donations.tsx
1. donation page was created using stripe, not open to public since it's not functioning. (FYI It's under my bank account! don't try to donate)
2. still need the backend side done
3. access by going to '...url/donate'
=> frontend side of donations page created

src/Donations/CheckoutForm.tsx, src/Donations/Donations.css, src/Donations/Donations.tsx, src/Header/Header.tsx
1. donation page is ready to go!
=> donation page up and running

src/Homepage/Homepage.css, src/Homepage/Homepage.tsx, src/Provider-login/LoginPage.tsx
1. minor touch ups for homepage (img size adjustments)
=> minor touch ups for homepage

src/Header/Header.tsx
1. Changes the logo size for all screens and contains it rather than fits so it doesn't stretch vertically. 
=> updated logo size for all screen sizes

src/Homepage/Homepage.css, src/Homepage/Homepage.tsx
1. Changed the color of the homepage modal to less aggressive color
2. Added a donation button in homepage with a pulse animation
=> changed color of homepage modal, and added a floating donation button

src/Homepage/Homepage.css, src/Homepage/Homepage.tsx
1. fixed the size of the modal to fit the window size
=> fixed modal to fit the window size

src/ContactUs/ContactUs.css, src/ContactUs/ContactUs.tsx, src/Donations/Donations.css, src/Donations/Donations.tsx, src/Footer/Footer.tsx, src/Homepage/Homepage.tsx, src/Provider-login/LoginPage.css
1. Updates wording on the homepage to include individuals/children.
2. Adds a link to the footer for our linkedIn profile.
3. Updates the donation page with a message for donators.
4. Added email on the contact us page and changed the button/link colors. 
=> Minore updates/jw

src/Donations/CheckoutForm.tsx, src/Donations/Donations.tsx
1. Trying something with adding google and apple pay since the domain has to be registered and using https.
=> hopefully add apple and google pay as options

src/Homepage/Homepage.tsx, src/Providers-page/ProvidersPage.tsx
1. Updated maintenance message til Sunday 22DEC2024
=> updated maintenance message

src/Providers-page/GoogleMap.tsx, src/Providers-page/ProviderModal.tsx
1. Conditionally render the map: if providers don’t have a physical address, display a map of the USA instead of the entire world.
=> it will show the map of the US for providers without address

src/Homepage/Homepage.tsx, src/Providers-page/ProviderCard.css, src/Providers-page/ProviderCard.tsx, src/Providers-page/ProvidersPage.css, src/Providers-page/ProvidersPage.tsx
1. removed maintenance message
2. brought back the old welcome message
=> removed maintenance message and brought back old message

src/Providers-page/ProviderCard.tsx
1. Removes the accidental "Proud Sponsor" message for all providers.
=> commented out proud sponsor text for providers

src/Homepage/Homepage.tsx
1. removed "scheduled maintenance" on the popup 
=> removed scheduled maintenance

src/Provider-edit/InsuranceModal.tsx, src/SuperAdmin/SuperAdmin.tsx, src/SuperAdmin/SuperAdminAddInsurances.tsx, src/Utility/ApiCall.ts, src/Utility/Types.ts
1. Updates the super admin panel to show add insurance button option.
2. Adds a new component to fully utilize CRUD functionality for insurances. There is a current list that shows all insurances and can be filtered before adding in a new one and will update with the new names after hitting submit.
3. Updates the insurance modal to sort alphabetically and to use all insurances rather than a hard coded list (third screenshot).
4. The new component is only used inside the super admin route and has logic to ensure names aren't added more than once. 
=> Add insurances form/jw

src/Donations/CheckoutForm.tsx, src/FavoriteProviders-page/FavoriteProviders.tsx, src/Providers-page/ProviderCard.css, src/Providers-page/ProviderModal.tsx, src/Providers-page/ProvidersPage.tsx, src/Signup/ProviderCheckoutForm.tsx, src/Signup/Signup.css, src/Signup/Signup.tsx, src/Signup/SignupModal.css, src/Signup/SignupModal.tsx, src/Utility/Types.ts
1. Changes the signup page to include a plan choice for providers (this URL isn't reachable from the button but the endpoint does work if you change it).
2. Updates the provider modal card to have locations on a separate tab since some providers have several locations and so the details page doesn't get too long.
3. Moved in the create functionality from the super admin. (it won't work due to not being logged in but the layout is there waiting for the signup endpoint from BE.
=> Provider signup/jw

src/App/App.css, src/Provider-edit/ProviderEdit.tsx, src/Provider-login/LoginPage.css, src/Provider-login/LoginPage.tsx, src/Providers-page/ProvidersPage.tsx, src/SuperAdmin/SuperAdminEdit.tsx
1. Adds in styling changes for the providers card, search bar, and providers page.
2. Updates all buttons to have the pointer cursor.
3. Fixes the search filter for ages to work appropriately. 
=> Styling updates/jw

src/Providers-page/SearchBar.tsx, src/Resources/Resources.css, src/Resources/Resources.tsx
=> minor updated

src/Header/Header.tsx, src/Homepage/Homepage.css, src/Homepage/Homepage.tsx
1. Updates homepage styling.
2. Adds different icons for the homepage buttons.
=> restyling of the homepage

src/Donations/Donations.tsx
1. Updates the donations page with the new PO box. 
=> updated PO box address

src/Signup/Signup.css, src/Signup/Signup.tsx
=> updates for mobile view

src/Provider-edit/ProviderEdit.tsx, src/Provider-edit/components/CreateLocation.tsx, src/Provider-edit/components/EditLocation.tsx, src/Providers-page/ProviderModal.tsx, src/Providers-page/ProvidersPage.tsx, src/Providers-page/SearchBar.tsx, src/Signup/SignupModal.tsx, src/SuperAdmin/SuperAdmin.tsx, src/SuperAdmin/SuperAdminEdit.tsx, src/Utility/Types.ts
1. Updates to new provider information for waitlist. 
2. 
=> updates to new location waitlist

src/Signup/Signup.css, src/Signup/SignupModal.tsx
1. Styling updates and change of email layout for registration. 
2. 
=> updates to emailJS and different styling for signup modal and page

src/ContactUs/ContactUs.tsx, src/Providers-page/ProvidersPage.tsx, src/Providers-page/SearchBar.tsx
1. Updated emails.
2. Added toast info box on providers page to grab peoples attention for missing information and to register if necessary. 
=> toast updates and new email changes

public/index.html, public/sw.js, src/AboutUs/AboutUs.tsx, src/Header/Header.tsx, src/Homepage/Homepage.tsx, src/Provider-edit/AuthModal.tsx, src/Signup/Signup.css, src/Signup/SignupModal.tsx, src/Utility/ApiCall.ts, src/Utility/networkUtils.ts
1. Mobile errors for site load.
2. Layout for signup page on mobile view 
=> mobile errors updates and stlying changes for mobile

public/index.html, public/mobile-debug.html, src/index.tsx
1. Updates service worker to see if that's causing the mobile issues. 
2. Fixes API for google reviews. 
=> mobile deployment bug catcher and API key updates for actual site

src/App/App.tsx, src/Donations/Donations.tsx, src/Providers-page/GoogleReviewsSection.tsx, src/Utility/GooglePlacesAPI.ts
1. fixes mobile bug issues and updates google api for production and deployment 
2. 
=> updates for issues

src/Provider-edit/ProviderEdit.tsx, src/Provider-edit/components/EditLocation.tsx, src/SuperAdmin/SuperAdminCreate.tsx, src/SuperAdmin/SuperAdminEdit.tsx
1. Updates to toast messages rendering. 
2. Updates for rendering and saving data. 
=> updates to toast messages and rendering of data

src/Signup/SignupModal.tsx
1. Updates for registrant email
2. Updates for focus on states/counties
=> Updates to singup modal

public/index.html
1. Removes old chat bot and adds in live agent one. 
2. 
=> Updated different agent to have live chat

src/App/App.tsx, src/ForgotPassword/ForgotPassword.tsx, src/PasswordReset/PasswordReset.tsx
=> update url path for reset token

package-lock.json, src/PasswordReset/PasswordReset.tsx
🐛 BUG FIX:
- Changed HTTP method from PUT to PATCH for password reset endpoint
- Frontend was using wrong HTTP method causing 404 errors
- Now correctly uses PATCH /api/v1/password_resets as expected by backend
✅ RESULT:
- Password reset functionality should now work correctly
- Users can successfully reset their passwords without 404 errors
1. 
2. 
=> 🔧 Fix Password Reset 404 Error

src/PasswordReset/PasswordReset.tsx, src/Utility/ApiCall.ts
1. Updates email functionality for forgot password 
=> Fix password reset API endpoints - add missing /api prefix

public/index.html, src/Header/Header.css, src/Header/Header.tsx, src/Provider-edit/ProviderEdit.tsx, src/SuperAdmin/SuperAdmin.tsx
- Fixed header logo sizing to prevent stretching and improve desktop appearance
- Improved navbar navigation alignment and spacing for professional look
- Enhanced favicon quality with proper sizing to eliminate pixelation
- Reverted to original ASL_5.2.png logo as requested
- Added CSS improvements for consistent navigation button styling
- Fixed SuperAdmin logout button positioning for better mobile accessibility
=> UI/UX improvements: logo sizing, navbar alignment, and favicon quality

src/Providers-page/ProvidersPage.tsx, src/SuperAdmin/SuperAdmin.tsx
- Add console logging to ProvidersPage useEffect to track API calls
- Add console logging to SuperAdmin fetchAllProviders to track admin API calls
- Help diagnose why app is stuck in loading state and providers not loading
- API endpoint is working (confirmed with curl test)
1. 
2. 
=> Add debugging logs to diagnose loading and providers issues
